
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def BASE_LAPSE_RATES(LAPSE_CODE, POL_YR, REN_POL_TERM_Y
			, LAPSE_RATE_BE):
	if (LAPSE_CODE==999999) or (POL_YR > REN_POL_TERM_Y):
		return 0
	else:
		return LAPSE_RATE_BE/100


@njit(nogil=True, parallel=True, cache=True)
def wrapped_BASE_LAPSE_RATES(LAPSE_CODE,POL_YR,REN_POL_TERM_Y,LAPSE_RATE_BE):
	arr_BASE_LAPSE_RATES=np.zeros(POL_YR.shape,dtype=float64)
	for y in prange(POL_YR.shape[0]):
		for t in range(POL_YR.shape[1]):
			arr_BASE_LAPSE_RATES[y,t]=BASE_LAPSE_RATES(LAPSE_CODE[y,0],POL_YR[y,t],REN_POL_TERM_Y[y,0],LAPSE_RATE_BE[y,t])
	return arr_BASE_LAPSE_RATES
