
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def BASE_DEATH_RATES(MORT_RATE_BE, POL_YR, REN_POL_TERM_Y, ANN_TERM_Y):
	if POL_YR > (REN_POL_TERM_Y + ANN_TERM_Y):
		return 0
	else:
		return MORT_RATE_BE


@njit(nogil=True, parallel=True, cache=True)
def wrapped_BASE_DEATH_RATES(MORT_RATE_BE,POL_YR,REN_POL_TERM_Y,ANN_TERM_Y):
	arr_BASE_DEATH_RATES=np.zeros(MORT_RATE_BE.shape,dtype=float64)
	for y in prange(MORT_RATE_BE.shape[0]):
		for t in range(MORT_RATE_BE.shape[1]):
			arr_BASE_DEATH_RATES[y,t]=BASE_DEATH_RATES(MORT_RATE_BE[y,t],POL_YR[y,t],REN_POL_TERM_Y[y,0],ANN_TERM_Y[y,0])
	return arr_BASE_DEATH_RATES
