
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def CALENDAR_YEAR(T,ENTRY_YEAR,ENTRY_MONTH):
	return (ENTRY_YEAR*12+ENTRY_MONTH+T-2)//12


@njit(nogil=True, parallel=True, cache=True)
def wrapped_CALENDAR_YEAR(T,ENTRY_YEAR,ENTRY_MONTH):
	arr_CALENDAR_YEAR=np.zeros(T.shape,dtype=int32)
	for y in prange(T.shape[0]):
		for t in range(T.shape[1]):
			arr_CALENDAR_YEAR[y,t]=CALENDAR_YEAR(T[y,t],ENTRY_YEAR[y,0],ENTRY_MONTH[y,0])
	return arr_CALENDAR_YEAR
