
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def COMM_CB_CODE_patch(COMM_CB_CODE):
	if COMM_CB_CODE==999999:
		return 1
	else:
		return COMM_CB_CODE


@njit(nogil=True, parallel=True, cache=True)
def wrapped_COMM_CB_CODE_patch(COMM_CB_CODE):
	arr_COMM_CB_CODE_patch=np.zeros((COMM_CB_CODE.shape[0],1),dtype=int32)
	for y in prange(COMM_CB_CODE.shape[0]):
		arr_COMM_CB_CODE_patch[y,0]=COMM_CB_CODE_patch(COMM_CB_CODE[y,0])
	return arr_COMM_CB_CODE_patch
