
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def COMM_AG_FAC_1_derived(COMM_AG_FAC_1,COMM_ID):
	if COMM_ID==5:
		return COMM_AG_FAC_1
	else:
		return 1


@njit(nogil=True, parallel=True, cache=True)
def wrapped_COMM_AG_FAC_1_derived(COMM_AG_FAC_1,COMM_ID):
	arr_COMM_AG_FAC_1_derived=np.zeros((COMM_AG_FAC_1.shape[0],1),dtype=int32)
	for y in prange(COMM_AG_FAC_1.shape[0]):
		arr_COMM_AG_FAC_1_derived[y,0]=COMM_AG_FAC_1_derived(COMM_AG_FAC_1[y,0],COMM_ID[y,0])
	return arr_COMM_AG_FAC_1_derived
