
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def COMM_MILAGE_RATE(COMM_MILE_PC_derived,T,REN_POL_TERM_Y):
	if T>REN_POL_TERM_Y*12:
		return 0
	else:
		return COMM_MILE_PC_derived


@njit(nogil=True, parallel=True, cache=True)
def wrapped_COMM_MILAGE_RATE(COMM_MILE_PC_derived,T,REN_POL_TERM_Y):
	arr_COMM_MILAGE_RATE=np.zeros(T.shape,dtype=float64)
	for y in prange(T.shape[0]):
		for t in range(T.shape[1]):
			arr_COMM_MILAGE_RATE[y,t]=COMM_MILAGE_RATE(COMM_MILE_PC_derived[y,0],T[y,t],REN_POL_TERM_Y[y,0])
	return arr_COMM_MILAGE_RATE
