
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def COMM_BON_PC_derived(COMM_BON_BE,T,REN_POL_TERM_Y):
	if T>REN_POL_TERM_Y*12:
		return 0
	else:
		return COMM_BON_BE


@njit(nogil=True, parallel=True, cache=True)
def wrapped_COMM_BON_PC_derived(COMM_BON_BE,T,REN_POL_TERM_Y):
	arr_COMM_BON_PC_derived=np.zeros(COMM_BON_BE.shape,dtype=float64)
	for y in prange(COMM_BON_BE.shape[0]):
		for t in range(COMM_BON_BE.shape[1]):
			arr_COMM_BON_PC_derived[y,t]=COMM_BON_PC_derived(COMM_BON_BE[y,t],T[y,t],REN_POL_TERM_Y[y,0])
	return arr_COMM_BON_PC_derived
