
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def DEATH_RATE_MONTHLY(DEATH_RATE_ANNUAL,MORT_RATE_MAX_AGE,ATTAINED_AGE,POL_MTH):
	if MORT_RATE_MAX_AGE==ATTAINED_AGE:
		#THIS IS REALLY HACKY! WHOEVER IS LEFT IS KILLED OFF!
		extra_factor=(1-POL_MTH/12)
	else:
		extra_factor=1
	return (1-(1-DEATH_RATE_ANNUAL)**(1/12))*extra_factor


@njit(nogil=True, parallel=True, cache=True)
def wrapped_DEATH_RATE_MONTHLY(DEATH_RATE_ANNUAL,MORT_RATE_MAX_AGE,ATTAINED_AGE,POL_MTH):
	arr_DEATH_RATE_MONTHLY=np.zeros(DEATH_RATE_ANNUAL.shape,dtype=float64)
	for y in prange(DEATH_RATE_ANNUAL.shape[0]):
		for t in range(DEATH_RATE_ANNUAL.shape[1]):
			arr_DEATH_RATE_MONTHLY[y,t]=DEATH_RATE_MONTHLY(DEATH_RATE_ANNUAL[y,t],MORT_RATE_MAX_AGE[y,0],ATTAINED_AGE[y,t],POL_MTH[y,t])
	return arr_DEATH_RATE_MONTHLY
