
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def DECREMENT_WOP_EXPERIENCE(DEC_WOP_CODE, POL_YR, REN_POL_TERM_Y, ANN_TERM_Y, WOP_EXP_FAC_BE):
	if DEC_WOP_CODE==999999:
		return 0
	else:
		if POL_YR>(REN_POL_TERM_Y+ANN_TERM_Y):
			return 0
		else:
			return WOP_EXP_FAC_BE/100


@njit(nogil=True, parallel=True, cache=True)
def wrapped_DECREMENT_WOP_EXPERIENCE(DEC_WOP_CODE,POL_YR,REN_POL_TERM_Y,ANN_TERM_Y,WOP_EXP_FAC_BE):
	arr_DECREMENT_WOP_EXPERIENCE=np.zeros(POL_YR.shape,dtype=float64)
	for y in prange(POL_YR.shape[0]):
		for t in range(POL_YR.shape[1]):
			arr_DECREMENT_WOP_EXPERIENCE[y,t]=DECREMENT_WOP_EXPERIENCE(DEC_WOP_CODE[y,0],POL_YR[y,t],REN_POL_TERM_Y[y,0],ANN_TERM_Y[y,0],WOP_EXP_FAC_BE[y,t])
	return arr_DECREMENT_WOP_EXPERIENCE
