
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def DECREMENT_WOP_RATES_MONTHLY(DECREMENT_WOP_RATES_ANNUAL):
	return 1-(1-DECREMENT_WOP_RATES_ANNUAL)**(1/12)


@njit(nogil=True, parallel=True, cache=True)
def wrapped_DECREMENT_WOP_RATES_MONTHLY(DECREMENT_WOP_RATES_ANNUAL):
	arr_DECREMENT_WOP_RATES_MONTHLY=np.zeros(DECREMENT_WOP_RATES_ANNUAL.shape,dtype=float64)
	for y in prange(DECREMENT_WOP_RATES_ANNUAL.shape[0]):
		for t in range(DECREMENT_WOP_RATES_ANNUAL.shape[1]):
			arr_DECREMENT_WOP_RATES_MONTHLY[y,t]=DECREMENT_WOP_RATES_MONTHLY(DECREMENT_WOP_RATES_ANNUAL[y,t])
	return arr_DECREMENT_WOP_RATES_MONTHLY
