
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def DURATIONIF_M(ENTRY_YEAR, ENTRY_MONTH, val_yr, val_mth):
	return (val_yr - ENTRY_YEAR)*12 + val_mth - ENTRY_MONTH+1


@njit(nogil=True, parallel=True, cache=True)
def wrapped_DURATIONIF_M(ENTRY_YEAR,ENTRY_MONTH,val_yr,val_mth):
	arr_DURATIONIF_M=np.zeros((ENTRY_YEAR.shape[0],1),dtype=int32)
	for y in prange(ENTRY_YEAR.shape[0]):
		arr_DURATIONIF_M[y,0]=DURATIONIF_M(ENTRY_YEAR[y,0],ENTRY_MONTH[y,0],val_yr[0,0],val_mth[0,0])
	return arr_DURATIONIF_M
