
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def FISCAL_MONTH(ENTRY_MONTH,COM_YEAR_END,T):
	return 1+(ENTRY_MONTH-1-COM_YEAR_END+T+23)%12


@njit(nogil=True, parallel=True, cache=True)
def wrapped_FISCAL_MONTH(ENTRY_MONTH,COM_YEAR_END,T):
	arr_FISCAL_MONTH=np.zeros(T.shape,dtype=int32)
	for y in prange(T.shape[0]):
		for t in range(T.shape[1]):
			arr_FISCAL_MONTH[y,t]=FISCAL_MONTH(ENTRY_MONTH[y,0],COM_YEAR_END[0,0],T[y,t])
	return arr_FISCAL_MONTH
