
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def FISCAL_YEAR(CALENDAR_YEAR,CALENDAR_MONTH,FISCAL_MONTH):
	if FISCAL_MONTH>=CALENDAR_MONTH:
		return CALENDAR_YEAR-1
	else:
		return CALENDAR_YEAR


@njit(nogil=True, parallel=True, cache=True)
def wrapped_FISCAL_YEAR(CALENDAR_YEAR,CALENDAR_MONTH,FISCAL_MONTH):
	arr_FISCAL_YEAR=np.zeros(CALENDAR_YEAR.shape,dtype=int32)
	for y in prange(CALENDAR_YEAR.shape[0]):
		for t in range(CALENDAR_YEAR.shape[1]):
			arr_FISCAL_YEAR[y,t]=FISCAL_YEAR(CALENDAR_YEAR[y,t],CALENDAR_MONTH[y,t],FISCAL_MONTH[y,t])
	return arr_FISCAL_YEAR
