
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def LAPSE_CHAN_IDX(LAPSE_CHAN_IND):
	if LAPSE_CHAN_IND==0:
		return 999999
	else:
		return LAPSE_CHAN_IND


@njit(nogil=True, parallel=True, cache=True)
def wrapped_LAPSE_CHAN_IDX(LAPSE_CHAN_IND):
	arr_LAPSE_CHAN_IDX=np.zeros((LAPSE_CHAN_IND.shape[0],1),dtype=int64)
	for y in prange(LAPSE_CHAN_IND.shape[0]):
		arr_LAPSE_CHAN_IDX[y,0]=LAPSE_CHAN_IDX(LAPSE_CHAN_IND[y,0])
	return arr_LAPSE_CHAN_IDX
