
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def LAPSE_RATE_MONTHLY(LAPSE_RATE_ANNUAL):
	return 1-(1-LAPSE_RATE_ANNUAL)**(1/12)


@njit(nogil=True, parallel=True, cache=True)
def wrapped_LAPSE_RATE_MONTHLY(LAPSE_RATE_ANNUAL):
	arr_LAPSE_RATE_MONTHLY=np.zeros(LAPSE_RATE_ANNUAL.shape,dtype=float64)
	for y in prange(LAPSE_RATE_ANNUAL.shape[0]):
		for t in range(LAPSE_RATE_ANNUAL.shape[1]):
			arr_LAPSE_RATE_MONTHLY[y,t]=LAPSE_RATE_MONTHLY(LAPSE_RATE_ANNUAL[y,t])
	return arr_LAPSE_RATE_MONTHLY
