
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def LAPSE_PAD_PC(LAPSE_PAD_CODE):
	if LAPSE_PAD_CODE == 999999:
		return 0
	else:
	#THIS CODE IS BROKEN IN THE SPREADSHEET
		return 0


@njit(nogil=True, parallel=True, cache=True)
def wrapped_LAPSE_PAD_PC(LAPSE_PAD_CODE):
	arr_LAPSE_PAD_PC=np.zeros((LAPSE_PAD_CODE.shape[0],1),dtype=float64)
	for y in prange(LAPSE_PAD_CODE.shape[0]):
		arr_LAPSE_PAD_PC[y,0]=LAPSE_PAD_PC(LAPSE_PAD_CODE[y,0])
	return arr_LAPSE_PAD_PC
