
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def MORT_AGE_col(JUV_IND,ATTAINED_AGE,ATTAINED_AGE_Y):
	if JUV_IND==1:
		return ATTAINED_AGE_Y
	else:
		return ATTAINED_AGE


@njit(nogil=True, parallel=True, cache=True)
def wrapped_MORT_AGE_col(JUV_IND,ATTAINED_AGE,ATTAINED_AGE_Y):
	arr_MORT_AGE_col=np.zeros(ATTAINED_AGE.shape,dtype=int32)
	for y in prange(ATTAINED_AGE.shape[0]):
		for t in range(ATTAINED_AGE.shape[1]):
			arr_MORT_AGE_col[y,t]=MORT_AGE_col(JUV_IND[y,0],ATTAINED_AGE[y,t],ATTAINED_AGE_Y[y,t])
	return arr_MORT_AGE_col
