
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def MORTALITY_SELECTION_FACTOR_col(BASE_POL_TERM_Y, RENEWAL_COUNT, max_mort_sel_lkup_yr, POL_YR):
	return max(
		min(POL_YR+BASE_POL_TERM_Y*RENEWAL_COUNT,max_mort_sel_lkup_yr)
			,1)


@njit(nogil=True, parallel=True, cache=True)
def wrapped_MORTALITY_SELECTION_FACTOR_col(BASE_POL_TERM_Y,RENEWAL_COUNT,max_mort_sel_lkup_yr,POL_YR):
	arr_MORTALITY_SELECTION_FACTOR_col=np.zeros(POL_YR.shape,dtype=int32)
	for y in prange(POL_YR.shape[0]):
		for t in range(POL_YR.shape[1]):
			arr_MORTALITY_SELECTION_FACTOR_col[y,t]=MORTALITY_SELECTION_FACTOR_col(BASE_POL_TERM_Y[y,0],RENEWAL_COUNT[y,0],max_mort_sel_lkup_yr[0,0],POL_YR[y,t])
	return arr_MORTALITY_SELECTION_FACTOR_col
