
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def MORT_RATE_MAX_AGE(SEX):
	if SEX==0:
		return 106
	else:
		return 109


@njit(nogil=True, parallel=True, cache=True)
def wrapped_MORT_RATE_MAX_AGE(SEX):
	arr_MORT_RATE_MAX_AGE=np.zeros((SEX.shape[0],1),dtype=int32)
	for y in prange(SEX.shape[0]):
		arr_MORT_RATE_MAX_AGE[y,0]=MORT_RATE_MAX_AGE(SEX[y,0])
	return arr_MORT_RATE_MAX_AGE
