
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def MORT_SEX_IDX(JUV_IND,MORT_SEX_IND, SEX2, SEX):
#THIS HAS A CMT LOOKUP IN THE BE SECTION IN THE EXCEL. IS THIS A MISTAKE?!
	if MORT_SEX_IND==0:
		return 999999
	else:
		if JUV_IND==1:
			return SEX2
		else:
			return SEX


@njit(nogil=True, parallel=True, cache=True)
def wrapped_MORT_SEX_IDX(JUV_IND,MORT_SEX_IND,SEX2,SEX):
	arr_MORT_SEX_IDX=np.zeros((JUV_IND.shape[0],1),dtype=int32)
	for y in prange(JUV_IND.shape[0]):
		arr_MORT_SEX_IDX[y,0]=MORT_SEX_IDX(JUV_IND[y,0],MORT_SEX_IND[y,0],SEX2[y,0],SEX[y,0])
	return arr_MORT_SEX_IDX
