
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def MORT_SMK_IDX(JUV_IND,MORT_SMK_IND, SMOKER_STAT):
	if MORT_SMK_IND==0:
		return 999999
	else:
		return SMOKER_STAT


@njit(nogil=True, parallel=True, cache=True)
def wrapped_MORT_SMK_IDX(JUV_IND,MORT_SMK_IND,SMOKER_STAT):
	arr_MORT_SMK_IDX=np.zeros((JUV_IND.shape[0],1),dtype=int32)
	for y in prange(JUV_IND.shape[0]):
		arr_MORT_SMK_IDX[y,0]=MORT_SMK_IDX(JUV_IND[y,0],MORT_SMK_IND[y,0],SMOKER_STAT[y,0])
	return arr_MORT_SMK_IDX
