
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def NO_LAPSE(NO_HTHY_SURRS,NO_WP_SURRS):
	return NO_HTHY_SURRS+NO_WP_SURRS


@njit(nogil=True, parallel=True, cache=True)
def wrapped_NO_LAPSE(NO_HTHY_SURRS,NO_WP_SURRS):
	arr_NO_LAPSE=np.zeros(NO_HTHY_SURRS.shape,dtype=float64)
	for y in prange(NO_HTHY_SURRS.shape[0]):
		for t in range(NO_HTHY_SURRS.shape[1]):
			arr_NO_LAPSE[y,t]=NO_LAPSE(NO_HTHY_SURRS[y,t],NO_WP_SURRS[y,t])
	return arr_NO_LAPSE
