
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def NO_POLS_IFSM(NO_HTHY_POLS_IFSM,NO_WP_POLS_IFSM):
	return NO_HTHY_POLS_IFSM+NO_WP_POLS_IFSM


@njit(nogil=True, parallel=True, cache=True)
def wrapped_NO_POLS_IFSM(NO_HTHY_POLS_IFSM,NO_WP_POLS_IFSM):
	arr_NO_POLS_IFSM=np.zeros(NO_HTHY_POLS_IFSM.shape,dtype=float64)
	for y in prange(NO_HTHY_POLS_IFSM.shape[0]):
		for t in range(NO_HTHY_POLS_IFSM.shape[1]):
			arr_NO_POLS_IFSM[y,t]=NO_POLS_IFSM(NO_HTHY_POLS_IFSM[y,t],NO_WP_POLS_IFSM[y,t])
	return arr_NO_POLS_IFSM
