
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def POLICY_YR_RESET_AT_RENEWAL(POL_YR, POL_TERM_Y):
	if POL_TERM_Y==0:
		return 0
	else:
		return ((POL_YR+POL_TERM_Y-1)%POL_TERM_Y)+1


@njit(nogil=True, parallel=True, cache=True)
def wrapped_POLICY_YR_RESET_AT_RENEWAL(POL_YR,POL_TERM_Y):
	arr_POLICY_YR_RESET_AT_RENEWAL=np.zeros(POL_YR.shape,dtype=int64)
	for y in prange(POL_YR.shape[0]):
		for t in range(POL_YR.shape[1]):
			arr_POLICY_YR_RESET_AT_RENEWAL[y,t]=POLICY_YR_RESET_AT_RENEWAL(POL_YR[y,t],POL_TERM_Y[y,0])
	return arr_POLICY_YR_RESET_AT_RENEWAL
