
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def PREPAID_PREMIUM_PRESENT_VALUE(PPIA_NO_TIME,PPIA_DISCOUNT_RATE):
	if PPIA_DISCOUNT_RATE==0:
		return 0
	else:
		return ((1-(1+PPIA_DISCOUNT_RATE))**(1-PPIA_NO_TIME))/PPIA_DISCOUNT_RATE


@njit(nogil=True, parallel=True, cache=True)
def wrapped_PREPAID_PREMIUM_PRESENT_VALUE(PPIA_NO_TIME,PPIA_DISCOUNT_RATE):
	arr_PREPAID_PREMIUM_PRESENT_VALUE=np.zeros((PPIA_NO_TIME.shape[0],1),dtype=float64)
	for y in prange(PPIA_NO_TIME.shape[0]):
		arr_PREPAID_PREMIUM_PRESENT_VALUE[y,0]=PREPAID_PREMIUM_PRESENT_VALUE(PPIA_NO_TIME[y,0],PPIA_DISCOUNT_RATE[y,0])
	return arr_PREPAID_PREMIUM_PRESENT_VALUE
