
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def RC_BASE_PAYBL_PP(REN_T,RC_START_M,COMM_RATE_ADJ_PC,COMM_MODAL_FAC,PREM_INC_PP):
	if REN_T<RC_START_M:
		return 0
	else:
		return COMM_RATE_ADJ_PC*COMM_MODAL_FAC*PREM_INC_PP


@njit(nogil=True, parallel=True, cache=True)
def wrapped_RC_BASE_PAYBL_PP(REN_T,RC_START_M,COMM_RATE_ADJ_PC,COMM_MODAL_FAC,PREM_INC_PP):
	arr_RC_BASE_PAYBL_PP=np.zeros(REN_T.shape,dtype=float64)
	for y in prange(REN_T.shape[0]):
		for t in range(REN_T.shape[1]):
			arr_RC_BASE_PAYBL_PP[y,t]=RC_BASE_PAYBL_PP(REN_T[y,t],RC_START_M[0,0],COMM_RATE_ADJ_PC[y,t],COMM_MODAL_FAC[y,t],PREM_INC_PP[y,t])
	return arr_RC_BASE_PAYBL_PP
