
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def REN_COMM_S_AG_FAC(COMM_ID,REN_COMM_S_AG_FAC_1):
	if COMM_ID==5:
		return REN_COMM_S_AG_FAC_1
	else:
		return 1


@njit(nogil=True, parallel=True, cache=True)
def wrapped_REN_COMM_S_AG_FAC(COMM_ID,REN_COMM_S_AG_FAC_1):
	arr_REN_COMM_S_AG_FAC=np.zeros((COMM_ID.shape[0],1),dtype=float64)
	for y in prange(COMM_ID.shape[0]):
		arr_REN_COMM_S_AG_FAC[y,0]=REN_COMM_S_AG_FAC(COMM_ID[y,0],REN_COMM_S_AG_FAC_1[y,0])
	return arr_REN_COMM_S_AG_FAC
