
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def SP_IND(PREM_FREQ):
	if PREM_FREQ==0:
		return 1
	else:
		return 0


@njit(nogil=True, parallel=True, cache=True)
def wrapped_SP_IND(PREM_FREQ):
	arr_SP_IND=np.zeros((PREM_FREQ.shape[0],1),dtype=int32)
	for y in prange(PREM_FREQ.shape[0]):
		arr_SP_IND[y,0]=SP_IND(PREM_FREQ[y,0])
	return arr_SP_IND
