
#THIS CODE IS AUTO-GENERATED by timeloop_tempate, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def WOP_EXP_FAC_BE_col(POL_YR, MAX_EXP_LKUP_Y):
	return min(POL_YR,MAX_EXP_LKUP_Y)


@njit(nogil=True, parallel=True, cache=True)
def wrapped_WOP_EXP_FAC_BE_col(POL_YR,MAX_EXP_LKUP_Y):
	arr_WOP_EXP_FAC_BE_col=np.zeros(POL_YR.shape,dtype=int32)
	for y in prange(POL_YR.shape[0]):
		for t in range(POL_YR.shape[1]):
			arr_WOP_EXP_FAC_BE_col[y,t]=WOP_EXP_FAC_BE_col(POL_YR[y,t],MAX_EXP_LKUP_Y[0,0])
	return arr_WOP_EXP_FAC_BE_col
