
#THIS CODE IS AUTO-GENERATED by simple_template, DO NOT DIRECTLY EDIT UNLESS YOU KNOW WHAT YOU ARE DOING!

from numba import njit, void, prange
import numpy as np
import math
from numpy import float64, int32, int64

@njit(nogil=True, cache=True)
def WOP_EXP_SEX_IDX(DEC_WOP_EXP_SEX_IND,SEX):
	if DEC_WOP_EXP_SEX_IND==0:
		return 999999
	else:
		return SEX


@njit(nogil=True, parallel=True, cache=True)
def wrapped_WOP_EXP_SEX_IDX(DEC_WOP_EXP_SEX_IND,SEX):
	arr_WOP_EXP_SEX_IDX=np.zeros((DEC_WOP_EXP_SEX_IND.shape[0],1),dtype=int32)
	for y in prange(DEC_WOP_EXP_SEX_IND.shape[0]):
		arr_WOP_EXP_SEX_IDX[y,0]=WOP_EXP_SEX_IDX(DEC_WOP_EXP_SEX_IND[y,0],SEX[y,0])
	return arr_WOP_EXP_SEX_IDX
